name: ASP.NET CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-2019
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Enable .NET Framework 3.5
      run: |
        dism.exe /Online /Enable-Feature /FeatureName:NetFx3 /All

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore ChatGnocchiPastaTransformer.sln

    - name: Build the project
      run: msbuild ChatGnocchiPastaTransformer.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v3.5

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            combined.txt
            ./bin/*
